### ISSUE TITLE
python setup.py problems

### ISSUE THREAD

**Issue by philipus** [gsi-upm/soil#1]
got problems with installation soil (See below). I have python 2.x (anaconda, windows) installed.

Do you have any idea what I am doing wrong?
-----------------------------------------------------------------------

Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from soil import __version__
  File "C:\Users\ffloegel\soil\soil\soil\__init__.py", line 12, in <module>
    from . import agents
  File "C:\Users\ffloegel\soil\soil\soil\agents\__init__.py", line 25
    class BaseAgent(nxsim.BaseAgent, metaclass=MetaAgent):
                                              ^
SyntaxError: invalid syntax

**Comment by balkian** [comment]
Hi @philipus. I'm afraid soil is not compatible with python 2 because of one of the libraries we use (nxsim). However, it should be pretty straightforward to upgrade to python 3 using anaconda.

Our apologies for the inconvenience.

**Comment by philipus** [comment]
ok thx
