### ISSUE TITLE
installation problems

### ISSUE THREAD

**Issue by philipus** [gsi-upm/soil#2]
have got python 3.4 and updated all packages for. but still problems to install soil (see below). environment.py in line 54 is the problem

Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from soil import __version__
  File "..\soil\soil\soil\__init__.py", line 13, in <module>
    from . import simulation
  File "..\soil\soil\soil\simulation.py", line 17, in <module>
    from . import agents, utils, environment, basestring
  File "..\soil\soil\soil\environment.py", line 53
    a = atype(**kwargs, environment=self)
                      ^
SyntaxError: invalid syntax

Any Idea???

 @environment_agents.setter
    def environment_agents(self, environment_agents):
        # Set up environmental agent
        self._env_agents = {}
        for item in environment_agents:
            kwargs = deepcopy(item)
            atype = kwargs.pop('agent_type')
            kwargs['agent_id'] = kwargs.get('agent_id', atype.__name__)
            kwargs['state'] = kwargs.get('state', {})

            a = atype(**kwargs, environment=self)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^

            self._env_agents[a.id] = weakref.ref(a)

**Comment by balkian** [comment]
Thanks for reporting!

Apparently, python 3.4 doesn't accept the inversion of *args. I've been testing soil with python 3.5 and assumed there weren't any incompatibilities.

I've fixed this and a couple of expressions more in v0.9.7. The docker image now builds from python 3.4. All tests pass and it seems to work.

Let me know if you encounter any other issues. And feel free to close the issue if you manage to install it.

**Comment by philipus** [comment]
THX. It compiled!
