### ISSUE TITLE
Problems in running examples with windows OS

### ISSUE THREAD

**Issue by micgarau** [gsi-upm/soil#5]
Hello.
After installing soil on my windows OS (As pointed out in the previous issue, I forced pip install soil==1.4.1 soil" for avoiding conflicts), I get an error in running the examples:

>> soil pubcrawl.yml
NotADirectoryError: [WinError 267] The directory name is invalid: 'soil_output\\pubcrawl\\2020-06-10_10:36'

May it be that the path format when creating the directory is not being recognized by windows?

**Comment by balkian** [comment]
First of all, thank you for your interest in Soil.

You are right about the path format, indeed. Please, test version 0.14.8 and let us know if that fixes your problem.

**Comment by balkian** [comment]
I'm closing this. Feel free to reopen if the issue persists.

**Comment by micgarau** [comment]
Thank you. I forgot to answer because I decided to work in a linux VM for the moment, until I finish my development. I will then test a simulation in a windows machine and let you know.
