### ISSUE TITLE
random seed assignation before agent.setter

### ISSUE THREAD

**Issue by micgarau** [gsi-upm/soil#6]
Hi.
I am working with your soil library. Don't you agree that it would be more proper to assign the seed to random library before running the agents initialization in environment.py?

**Comment by balkian** [comment]
You are right, indeed. Thanks for spotting that!

I will fix it in the next release.

**Comment by micgarau** [comment]
Thank you. Now the simulations are actually reproducible when seed is given as configuration parameter.
